TIME-KICK: 30
NO-REGISTER: "§e§l☞ YOU HAVE NOT REGISTERED PLEASE /register TO REGISTER"
NO-LOGIN: "§e§l☞ YOU HAVE NOT LOG IN PLEASE LOG IN TO JOIN"
KICK-NO-LOGIN: "§e§l☞ LOGIN TIME EXPIRED YOU HAVE BEEN KICKED"
YOU-HAVE-REGISTERED: "§e§l☞ YOU HAVE REGISTERED"
REGISTERED-SUCCESS: "§e§l☞ SIGN UP SUCCESS"
UNREGISTER: "§e§l☞ YOU DON'T SIGN UP"
LOGIN-SUCCESS: "§e§l☞ LOGGED IN SUCCESSFULLY"
NAME-IS-NOT-REGISTERED: "§e§l☞ NAME YOU ENTER DID NOT GENERATE A PASSWORD"
CHECKPASS: "§e§l☞ {NAME} PASSWORD IS {PASSWORD}"
WRONG-PASSWORD: "§e§l☞ YOU ENTER THE WRONG PASSWORD"
USAGE-REGISTER: "§e§l☞ USAGE: /register <password>"
USAGE-LOGIN: "§e§l☞ USAGE: /login <password>"
USAGE-CHECK: "§e§l☞ USAGE: /checkpass <name>"
